
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chuy4
 */
public class Principal extends javax.swing.JFrame {
    
    private Clip clip;
    private FloatControl volumeControl;
    FondoPanel1 fondo1 = new FondoPanel1();
    private int cancion;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setContentPane(fondo1);
        initComponents();
        this.setTitle("Luz y sonido xaviers - Menú principal");
        this.setLocationRelativeTo(null);
        try {
            // Ruta del archivo de audio
            File audioFile = new File("src\\MUSICA\\1.wav");

            // Cargar el archivo de audio
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);

            // Obtener el clip de audio
            clip = AudioSystem.getClip();

            // Abrir el clip de audio y reproducirlo
            clip.open(audioStream);
            
            volumeControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
            
            clip.start();

        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
        PanelMusica2.setVisible(false);
        PanelVolumen2.setVisible(false);
        cancion = 1;
    }
    
    public void changeVolumeMas(float change) {
        if (volumeControl != null) {
            float currentVolume = volumeControl.getValue();
            float newVolume = currentVolume + change;
            newVolume = Math.min(volumeControl.getMaximum(), Math.max(volumeControl.getMinimum(), newVolume)); // Limitar al rango permitido
            volumeControl.setValue(newVolume);
            System.out.println("Volumen ajustado a: " + newVolume + " dB");
        }
    }
     
    public void changeVolumeMenos(float change) {
        if (volumeControl != null) {
            float currentVolume = volumeControl.getValue();
            float newVolume = currentVolume - change;
            newVolume = Math.min(volumeControl.getMaximum(), Math.max(volumeControl.getMinimum(), newVolume)); // Limitar al rango permitido
            volumeControl.setValue(newVolume);
            System.out.println("Volumen ajustado a: " + newVolume + " dB");
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel3 = new FondoPanel2();
        Titulo = new javax.swing.JPanel();
        PanelMusica1 = new javax.swing.JPanel();
        DetenerMusica = new javax.swing.JButton();
        AtrasMusica1 = new javax.swing.JButton();
        AdelanteMusica1 = new javax.swing.JButton();
        PanelMusica2 = new javax.swing.JPanel();
        IniciarMusica = new javax.swing.JButton();
        AtrasMusica2 = new javax.swing.JButton();
        AdelanteMusica2 = new javax.swing.JButton();
        PanelVolumen1 = new javax.swing.JPanel();
        Mas1 = new javax.swing.JButton();
        Menos1 = new javax.swing.JButton();
        PanelVolumen2 = new javax.swing.JPanel();
        Mas2 = new javax.swing.JButton();
        Menos2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new FondoPanel1();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        PanelPrincipal.setForeground(new java.awt.Color(242, 242, 242));
        PanelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        Titulo.setBackground(new java.awt.Color(174, 229, 154));
        Titulo.setOpaque(false);

        PanelMusica1.setOpaque(false);

        DetenerMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Musica1.png"))); // NOI18N
        DetenerMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetenerMusicaMouseClicked(evt);
            }
        });
        DetenerMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerMusicaActionPerformed(evt);
            }
        });

        AtrasMusica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Musica4.png"))); // NOI18N
        AtrasMusica1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtrasMusica1MouseClicked(evt);
            }
        });
        AtrasMusica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasMusica1ActionPerformed(evt);
            }
        });

        AdelanteMusica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Musica3.png"))); // NOI18N
        AdelanteMusica1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdelanteMusica1MouseClicked(evt);
            }
        });
        AdelanteMusica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdelanteMusica1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMusica1Layout = new javax.swing.GroupLayout(PanelMusica1);
        PanelMusica1.setLayout(PanelMusica1Layout);
        PanelMusica1Layout.setHorizontalGroup(
            PanelMusica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMusica1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AtrasMusica1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DetenerMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdelanteMusica1)
                .addContainerGap())
        );
        PanelMusica1Layout.setVerticalGroup(
            PanelMusica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMusica1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMusica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdelanteMusica1)
                    .addComponent(AtrasMusica1)
                    .addComponent(DetenerMusica))
                .addContainerGap())
        );

        PanelMusica2.setOpaque(false);

        IniciarMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Musica2.png"))); // NOI18N
        IniciarMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        IniciarMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarMusicaMouseClicked(evt);
            }
        });
        IniciarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarMusicaActionPerformed(evt);
            }
        });

        AtrasMusica2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Musica4.png"))); // NOI18N
        AtrasMusica2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AtrasMusica2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtrasMusica2MouseClicked(evt);
            }
        });
        AtrasMusica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasMusica2ActionPerformed(evt);
            }
        });

        AdelanteMusica2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Musica3.png"))); // NOI18N
        AdelanteMusica2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AdelanteMusica2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdelanteMusica2MouseClicked(evt);
            }
        });
        AdelanteMusica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdelanteMusica2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMusica2Layout = new javax.swing.GroupLayout(PanelMusica2);
        PanelMusica2.setLayout(PanelMusica2Layout);
        PanelMusica2Layout.setHorizontalGroup(
            PanelMusica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMusica2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AtrasMusica2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IniciarMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdelanteMusica2)
                .addContainerGap())
        );
        PanelMusica2Layout.setVerticalGroup(
            PanelMusica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMusica2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMusica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdelanteMusica2)
                    .addComponent(IniciarMusica)
                    .addComponent(AtrasMusica2))
                .addContainerGap())
        );

        PanelVolumen1.setOpaque(false);

        Mas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Volumen1.png"))); // NOI18N
        Mas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mas1ActionPerformed(evt);
            }
        });

        Menos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Volumen2.png"))); // NOI18N
        Menos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVolumen1Layout = new javax.swing.GroupLayout(PanelVolumen1);
        PanelVolumen1.setLayout(PanelVolumen1Layout);
        PanelVolumen1Layout.setHorizontalGroup(
            PanelVolumen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVolumen1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menos1)
                .addContainerGap())
        );
        PanelVolumen1Layout.setVerticalGroup(
            PanelVolumen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVolumen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVolumen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menos1)
                    .addComponent(Mas1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelVolumen2.setOpaque(false);

        Mas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Volumen1.png"))); // NOI18N
        Mas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mas2ActionPerformed(evt);
            }
        });

        Menos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Volumen2.png"))); // NOI18N
        Menos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVolumen2Layout = new javax.swing.GroupLayout(PanelVolumen2);
        PanelVolumen2.setLayout(PanelVolumen2Layout);
        PanelVolumen2Layout.setHorizontalGroup(
            PanelVolumen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVolumen2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menos2)
                .addContainerGap())
        );
        PanelVolumen2Layout.setVerticalGroup(
            PanelVolumen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVolumen2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVolumen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menos2)
                    .addComponent(Mas2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addGroup(TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                        .addComponent(PanelVolumen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelMusica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                        .addComponent(PanelVolumen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelMusica2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelVolumen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TituloLayout.createSequentialGroup()
                        .addGroup(TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelMusica1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelVolumen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelMusica2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LUZ Y SONIDO XAVIERS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DetenerMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerMusicaActionPerformed
        try {
            
            clip.stop();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DetenerMusicaActionPerformed

    private void DetenerMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetenerMusicaMouseClicked
        PanelMusica1.setVisible(false);
        PanelMusica2.setVisible(true);
        PanelVolumen1.setVisible(false);
        PanelVolumen2.setVisible(true);
    }//GEN-LAST:event_DetenerMusicaMouseClicked

    private void IniciarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarMusicaActionPerformed
        try {
            
            clip.start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_IniciarMusicaActionPerformed

    private void IniciarMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMusicaMouseClicked
        PanelMusica1.setVisible(true);
        PanelMusica2.setVisible(false);
        PanelVolumen1.setVisible(true);
        PanelVolumen2.setVisible(false);
    }//GEN-LAST:event_IniciarMusicaMouseClicked

    private void AdelanteMusica1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdelanteMusica1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdelanteMusica1MouseClicked

    private void AdelanteMusica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdelanteMusica1ActionPerformed

        try {
            cancion++;
            clip.stop();
            // Ruta del archivo de audio
            File audioFile = new File("src\\MUSICA\\"+cancion+".wav");

            // Cargar el archivo de audio
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);

            // Obtener el clip de audio
            clip = AudioSystem.getClip();

            // Abrir el clip de audio y reproducirlo
            clip.open(audioStream);
            
            volumeControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
            
            clip.start();

        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AdelanteMusica1ActionPerformed

    private void AtrasMusica1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMusica1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AtrasMusica1MouseClicked

    private void AtrasMusica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasMusica1ActionPerformed

        if(cancion == 1){
        
        }else{
            cancion--;
            try {
                clip.stop();
                // Ruta del archivo de audio
                File audioFile = new File("src\\MUSICA\\"+cancion+".wav");

                // Cargar el archivo de audio
                AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);

                // Obtener el clip de audio
                clip = AudioSystem.getClip();

                // Abrir el clip de audio y reproducirlo
                clip.open(audioStream);

                volumeControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);

                clip.start();

            } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_AtrasMusica1ActionPerformed

    private void AtrasMusica2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMusica2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AtrasMusica2MouseClicked

    private void AtrasMusica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasMusica2ActionPerformed
        if(cancion == 1){
        
        }else{
            cancion--;
            try {
                clip.stop();
                // Ruta del archivo de audio
                File audioFile = new File("src\\MUSICA\\"+cancion+".wav");

                // Cargar el archivo de audio
                AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);

                // Obtener el clip de audio
                clip = AudioSystem.getClip();

                // Abrir el clip de audio y reproducirlo
                clip.open(audioStream);

                volumeControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);

                clip.start();

            } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_AtrasMusica2ActionPerformed

    private void AdelanteMusica2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdelanteMusica2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdelanteMusica2MouseClicked

    private void AdelanteMusica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdelanteMusica2ActionPerformed
        
        try {
            cancion++;
            clip.stop();
            // Ruta del archivo de audio
            File audioFile = new File("src\\MUSICA\\"+cancion+".wav");

            // Cargar el archivo de audio
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);

            // Obtener el clip de audio
            clip = AudioSystem.getClip();

            // Abrir el clip de audio y reproducirlo
            clip.open(audioStream);
            
            volumeControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
            
            clip.start();

        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AdelanteMusica2ActionPerformed

    private void Mas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mas1ActionPerformed
        changeVolumeMas(5.0f);
    }//GEN-LAST:event_Mas1ActionPerformed

    private void Menos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menos1ActionPerformed
        changeVolumeMenos(5.0f);
    }//GEN-LAST:event_Menos1ActionPerformed

    private void Mas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mas2ActionPerformed
        changeVolumeMas(5.0f);
    }//GEN-LAST:event_Mas2ActionPerformed

    private void Menos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menos2ActionPerformed
        changeVolumeMenos(5.0f);
    }//GEN-LAST:event_Menos2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdelanteMusica1;
    private javax.swing.JButton AdelanteMusica2;
    private javax.swing.JButton AtrasMusica1;
    private javax.swing.JButton AtrasMusica2;
    private javax.swing.JButton DetenerMusica;
    private javax.swing.JButton IniciarMusica;
    private javax.swing.JButton Mas1;
    private javax.swing.JButton Mas2;
    private javax.swing.JButton Menos1;
    private javax.swing.JButton Menos2;
    private javax.swing.JPanel PanelMusica1;
    private javax.swing.JPanel PanelMusica2;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelVolumen1;
    private javax.swing.JPanel PanelVolumen2;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    class FondoPanel1 extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/IMAGENES/1.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
    class FondoPanel2 extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/IMAGENES/2.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
}

